# Training and Testing the model

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [2]:
data=pd.read_csv('Admission_Predict.csv')

In [3]:
data.head()

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research,Chance of Admit
0,1,337,118,4,4.5,4.5,9.65,1,0.92
1,2,324,107,4,4.0,4.5,8.87,1,0.76
2,3,316,104,3,3.0,3.5,8.00,1,0.72
3,4,322,110,3,3.5,2.5,8.67,1,0.80
4,5,314,103,2,2.0,3.0,8.21,0,0.65

In [4]:
x=data.drop(['Chance of Admit '],axis=1) 
y=data['Chance of Admit ']

In [5]:
from sklearn.model_selection import train_test_split 
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

In [6]:
x_train

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
361,362,334,116,4,4.0,3.5,9.54,1
63,64,315,107,2,4.0,3.0,8.50,1
6,7,321,109,3,3.0,4.0,8.20,1
285,286,331,116,5,4.0,4.0,9.26,1
175,176,320,111,4,4.5,3.5,8.87,1
...,...,...,...,...,...,...,...,...
330,331,327,113,3,3.5,3.0,8.66,1
130,131,339,114,5,4.0,4.5,9.76,1
198,199,311,104,3,4.5,4.5,8.43,0
171,172,334,117,5,4.0,4.5,9.07,1
342,343,308,106,3,3.0,3.0,8.24,0

In [7]:
y_train

361    0.93
63     0.56
6      0.75
285    0.93
175    0.85
       ...
330    0.80
130    0.96
198    0.70
171    0.89
342    0.58
Name: Chance of Admit , Length: 340, dtype: float64

In [8]:
x_test

,Serial No.,GRE Score,TOEFL Score,University Rating,SOP,LOR,CGPA,Research
271,272,299,96,2,1.5,2.0,7.86,0
92,93,298,98,2,4.0,3.0,8.03,0
125,126,300,100,3,2.0,3.0,8.66,1
399,400,333,117,4,5.0,4.0,9.66,1
379,380,311,99,1,2.5,3.0,8.43,1
60,61,309,100,2,3.0,3.0,8.10,0
46,47,329,114,5,4.0,5.0,9.30,1
362,363,338,115,5,4.5,5.0,9.23,1
258,259,326,102,4,5.0,5.0,8.76,1
365,366,330,114,4,4.5,3.0,9.17,1
155,156,312,109,3,3.0,3.0,8.69,0
290,291,307,105,2,2.5,3.0,7.65,0
397,398,330,116,4,5.0,4.5,9.45,1
254,255,321,114,4,4.0,5.0,9.12,0
2,3,316,104,3,3.0,3.5,8.00,1
65,66,325,112,4,3.5,3.5,8.92,0
85,86,319,103,4,4.5,3.5,8.66,0
288,289,314,104,4,5.0,5.0,9.02,0
77,78,301,99,2,3.0,2.0,8.22,0
306,307,323,110,3,4.0,3.5,9.10,1
300,301,309,106,2,2.5,2.5,8.00,0
19,20,303,102,3,3.5,3.0,8.50,0
116,117,299,102,3,4.0,3.5,8.62,0
230,231,313,104,3,4.0,4.5,8.65,0
366,367,320,104,3,3.5,4.5,8.34,1
391,392,318,106,3,2.0,3.0,8.65,0
235,236,326,111,5,4.5,4.0,9.23,1
86,87,315,106,3,4.5,3.5,8.42,0
228,229,318,112,3,4.0,3.5,8.67,0
303,304,323,107,3,3.5,3.5,8.55,1
178,179,309,108,3,2.5,3.0,8.12,0
12,13,328,112,4,4.0,4.5,9.10,1
317,318,300,99,1,1.0,2.5,8.01,0
227,228,312,110,2,3.5,3.0,8.53,0
356,357,327,109,3,3.5,4.0,8.77,1
75,76,329,114,2,2.0,4.0,8.56,1
357,358,301,104,2,3.5,3.5,7.89,1
325,326,326,116,3,3.5,4.0,9.14,1
343,344,305,103,2,2.5,3.5,8.13,0
7,8,308,101,2,3.0,4.0,7.90,0
359,360,321,107,2,2.0,1.5,8.44,0
301,302,319,108,2,2.5,3.0,8.76,0
54,55,322,110,3,3.0,3.5,8.00,0
17,18,319,106,3,4.0,3.0,8.00,1
272,273,294,95,1,1.5,1.5,7.64,0
248,249,324,110,3,3.5,4.0,8.87,1
103,104,317,104,2,4.5,4.0,8.47,0
241,242,317,103,2,2.5,2.0,8.15,0
353,354,300,102,3,3.5,2.5,8.17,0
89,90,316,109,4,4.5,3.5,8.76,1
48,49,321,110,3,3.5,5.0,8.85,1
66,67,327,114,3,3.0,3.0,9.02,0
114,115,311,105,3,3.5,3.0,8.45,1
61,62,307,101,3,4.0,3.0,8.20,0
209,210,301,104,3,3.5,4.0,8.12,1
113,114,320,110,2,4.0,3.5,8.56,0
158,159,306,106,2,2.0,2.5,8.14,0
339,340,324,107,5,3.5,4.0,8.66,1
51,52,312,100,2,1.5,3.5,7.90,1
159,160,297,100,1,1.5,2.0,7.90,0

In [9]:
y_test

271    0.54
92     0.34
125    0.64
399    0.95
379    0.71
60     0.48
46     0.86
362    0.91
258    0.77
365    0.86
155    0.77
290    0.58
397    0.91
254    0.85
2      0.72
65     0.55
85     0.76
288    0.82
77     0.64
306    0.79
300    0.62
19     0.62
116    0.56
230    0.73
366    0.74
391    0.71
235    0.88
86     0.72
228    0.71
303    0.73
178    0.72
12     0.78
317    0.58
227    0.64
356    0.79
75     0.72
357    0.68
325    0.81
343    0.59
7      0.68
359    0.81
301    0.66
54     0.70
17     0.65
272    0.49
248    0.80
103    0.57
241    0.65
353    0.63
89     0.74
48     0.82
66     0.61
114    0.59
61     0.47
209    0.68
113    0.72
158    0.61
339    0.81
51     0.56
159    0.52
Name: Chance of Admit , dtype: float64